"""empty message

Revision ID: f43d1613b364
Revises: 
Create Date: 2024-06-30 17:30:21.034869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43d1613b364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imobiliaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome_fantasia')
    )
    op.create_table('imovel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluguel', sa.Boolean(), nullable=True),
    sa.Column('venda', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.Enum('apartamento', 'casa', 'terreno', 'sala', name='tipoimovelenum'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('valor_venda', sa.Float(), nullable=True),
    sa.Column('valor_aluguel', sa.Float(), nullable=True),
    sa.Column('rua', sa.String(length=256), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=256), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('cidade', sa.String(length=256), nullable=False),
    sa.Column('estado', sa.String(length=256), nullable=False),
    sa.Column('imobiliaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imobiliaria_id'], ['imobiliaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imovel')
    op.drop_table('imobiliaria')
    # ### end Alembic commands ###
